# Generated by Django 4.1.2 on 2022-12-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TinyVideo_Tittle', models.CharField(max_length=20)),
                ('TinyVideo_Video', models.FileField(upload_to='tinyvideos')),
            ],
        ),
    ]
