# Generated by Django 4.1.2 on 2022-12-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smctrtinyvideoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinyvideo',
            name='Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
